import type { Metadata } from "next";
import localFont from "next/font/local";
import { Noto_Sans, EB_Garamond } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import {
	ClerkProvider,
	SignInButton,
	SignedIn,
	SignedOut,
	UserButton,
} from "@clerk/nextjs";

const noto = Noto_Sans({
	variable: "--font-notosans",
	subsets: ["latin"],
});

const eb = EB_Garamond({
	variable: "--font-eb",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${noto.variable} ${eb.variable} bg-offwhite font-noto antialiased`}>
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
